# config/routes/attributes.yaml
controllers:
    resource:
        path: ../../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

api_data:
    path: /api/formulaire
    controller: App\Controller\ApiController::handleForm

login:
    path: /login
    controller: App\Controller\ApiAuthController::handleForm