# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

controllers:
    resource: routing.controllers

api_data:
    path: /api/formulaire
    controller: App\Controller\ApiController::handleForm

add_todolist:
    path: /add_todolist
    controller: App\Controller\TodolistController::insertData

fetch_lists:
    path: /fetch
    controller: App\Controller\TodolistController::fetchList

fetch_todo_lists:
    path: /fetch/todolist/{id}
    controller: App\Controller\TodolistController::fetchTodolist
    requirements:
        id: '\d+'

add_todolist_item:
    path: /add_todolistItem/{id}
    controller: App\Controller\TodolistController::insertDataTodolistItem
    requirements:
        id: '\d+'

delete_todolist_item:
    path: /delete_todolistItem/{id}
    controller: App\Controller\TodolistController::deleteDataTodolistItem
    requirements:
        id: '\d+'

delete_todolist:
    path: /delete_todolist/{id}
    controller: App\Controller\TodolistController::deleteDataTodolist
    requirements:
        id: '\d+'

signup:
    path: /signup
    controller: App\Controller\ApiAuthController::CreateAccount

login:
    path: /login
    controller: App\Controller\ApiAuthController::login